# Change these first
owner: albismart # Your GitHub username
repo: uptime # Your Github repository name

# Add your sites here
sites:
  - name: CloudBase
    url: https://albismart.cloud/
  - name: Store
    url: https://albismart.store/
  - name: Gitlab
    url: https://gitlab.albismart.dev/
  - name: Continuous delivery
    url: https://compiler.albismart.dev/

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.albismart.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://cdn.albismart.cloud/logo.svg
  name: " "
  introTitle: "Status Page"
  introMessage: "Page for monitoring Albismart servers!"
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
