# Change these first
owner: albismart # Your GitHub username
repo: uptime # Your Github repository name

# Add your sites here
sites:
  - name: CloudBase
    url: 64.225.81.232
  - name: Store
    url: 157.245.64.40
  - name: Gitlab
    url: 128.199.44.156
  - name: Compiler
    url: 161.35.154.157

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.albismart.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://cdn.albismart.cloud/logo.svg
  name: 
  introTitle: "Status Page"
  introMessage: "Page for monitoring Albismart servers!"
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
